### ISSUE TITLE
Hide profile pictures in search results on LinkedIn

### ISSUE THREAD

**Issue by Mr0grog** [fureigh/unbias-me#13]
If you’re searching for someone on LinkedIn, profile pictures are still shown on the search results page:

<img width="412" alt="screen shot 2016-03-25 at 11 59 01 am" src="https://cloud.githubusercontent.com/assets/74178/14051587/711d24ec-f281-11e5-927e-c88acb559ee5.png">

It would probably be good to hide those, too.

**Comment by Mr0grog** [comment]
Ridiculously, it looks like the element is `.profile-img` instead of `.profile-picture`, which is the class on the individual profile page. ¯\_(ツ)_/¯

**Comment by fureigh** [comment]
Thanks, @Mr0grog!
