### ISSUE TITLE
Fetch permissions/ develop branch

### ISSUE THREAD

**Issue by jdetle** [fureigh/unbias-me#21]
Hi, I don't think I'm allowed to fetch from your repository for the purpose of keeping mine up to date. Could you help out and checkout a develop branch with more lax branch permissions?

**Comment by fureigh** [comment]
Hi @jdetle!

[Configuring a remote for your fork](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and then [syncing your fork](https://help.github.com/articles/syncing-a-fork/) should do the trick. (Note that in step 5 of the "syncing your fork" link, `rebase` may yield a cleaner result than `merge`.)

Please give that a shot and let me know how it goes. Thanks!

**Comment by jdetle** [comment]
This is super embarrassing but I was actually just missing a slash in the repo url.  Thank you so much!

**Comment by fureigh** [comment]
No worries! Glad you got it sorted out. :)
